version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: food_delivery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mahin@db
    ports:
      - "5432:5432"
  
  web:
    build: .
    command: python3 food_delivery/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
